# Generated by Django 5.2.7 on 2025-11-06 23:14

import django.db.models.deletion
import django_multitenant.mixins
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=50)),
                ('topic', models.CharField(db_index=True, max_length=255)),
                ('payload', models.JSONField()),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('dedup_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('dead', 'Dead-letter')], db_index=True, default='pending', max_length=20)),
                ('trace_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'topic', 'status'], name='events_even_organiz_bb70bd_idx'), models.Index(fields=['created_at'], name='events_even_created_52c227_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='uniq_org_idempotency_key')],
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
    ]
