# Generated by Django 5.2.7 on 2025-11-06 23:14

import django.db.models.deletion
import django_multitenant.fields
import django_multitenant.mixins
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlegraCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_key', models.CharField(max_length=255)),
                ('api_secret', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alegra_credentials', to='companies.company')),
            ],
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AlegraInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alegra_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('status', models.CharField(db_index=True, max_length=50)),
                ('payload_sent', models.JSONField()),
                ('response_received', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alegra_invoices', to='companies.company')),
                ('event', django_multitenant.fields.TenantForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alegra_invoice', to='events.event')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'alegra_id'), name='uniq_alegra_id_per_company')],
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
    ]
