# Generated by Django 5.2.7 on 2025-11-06 23:15

import django.db.models.deletion
import django_multitenant.mixins
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErpnextCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_key', models.CharField(max_length=255)),
                ('api_secret', models.CharField(max_length=255)),
                ('erpnext_site_url', models.URLField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erpnext_credentials', to='organizations.organization')),
            ],
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
    ]
